name: Release Snapshot

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: contains(github.event.pull_request.labels.*.name, 'publish')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Get Last Commit Message
        id: check_commit
        run: echo "LAST_COMMIT_MSG=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

      - name: Check Chore Commit
        id: check-chore-commit
        run: |
          if [[ "${{ env.LAST_COMMIT_MSG }}" == chore* ]]; then
            echo "SKIP_PUBLISH=true" >> $GITHUB_ENV
          else
            echo "SKIP_PUBLISH=false" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          scope: "@sidakram"

      - name: Generate .npmrc
        run: make create-npmrc

      - name: Install Dependencies
        if: env.SKIP_PUBLISH == 'false'
        run: npm ci

      - name: Version Bump
        if: env.SKIP_PUBLISH == 'false'
        run: |
          git fetch origin ${{ github.head_ref }}
          git rebase origin/${{ github.head_ref }}
          npm version prerelease --preid=pr${{ github.event.pull_request.number }} --no-git-tag-version --workspace=react-rendercov
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(release): bump version"

      - name: Build Package
        if: env.SKIP_PUBLISH == 'false'
        run: npm run build --workspace=react-rendercov

      - name: Read version
        id: version
        run: |
          VERSION=$(node -p "require('./packages/render-cov/package.json').version")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Publish Snapshot
        id: publish
        run: npm publish --tag dev --workspace=react-rendercov --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create tag and push
        run: |
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}
          git push origin HEAD:${{ github.head_ref }}
