name: Release Snapshot

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled


concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: contains(github.event.pull_request.labels.*.name, 'publish')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Get Last Commit Message
        id: check_commit
        run: echo "LAST_COMMIT_MSG=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

      - name: Check Chore Commit
        id: check-chore-commit
        run: |
          if [[ "${{ env.LAST_COMMIT_MSG }}" == chore* ]]; then
            echo "SKIP_PUBLISH=true" >> $GITHUB_ENV
          else
            echo "SKIP_PUBLISH=false" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        if: env.SKIP_PUBLISH == 'false'
        run: npm ci --prefer-offline --no-audit --no-fund --legacy-peer-deps

      - name: Version Bump
        if: env.SKIP_PUBLISH == 'false'
        run: |
          npm version prerelease --preid=pr${{ github.event.pull_request.number }} --no-git-tag-version
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(release): bump version"
          git push origin HEAD:${{ github.head_ref }}

      - name: Publish Snapshot
        id: publish
        run: npm publish --scope=@${{ github.repository_owner }} --tag dev --provenance --registry https://github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
